write_poem:
  description: >
    Write a woderful funny, light heartedpoem about my wonderful cat "Bakasura" that will make the reader smile in this {language} Language.
    Ensure the poem is engaging and adheres to the specified sentence count of {sentence_count}.
  expected_output: >
    A beautifully crafted poem in this {language} Language, with exactly {sentence_count} sentences.
  agent: poem_writer
